In [132]:
#1 Import numpy as np and print the version number.
import numpy as np
print(np.__version__)

1.18.1


In [133]:
#2 Create a 1D array of numbers from 0 to 9
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [134]:
#3 Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [135]:
#4 Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [136]:
#5 Replace all odd numbers in arr with -1 without changing arr
arr = np.arange(10)
where = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(where)


[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [137]:
#6 Create a 3×3 numpy array of all True’s"
arr = np.array([True, True,True, True,True, True,True, True,True ]).reshape(3,3)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [138]:
#7 Extract all odd numbers from arr
arr = np.arange(10)
print(arr[arr % 2 == 1])


[1 3 5 7 9]


In [139]:
#8 Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10).reshape(2,-1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [140]:
#9 How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [141]:
#10 Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [142]:
#11 Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [143]:
#12 Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [144]:
#13 From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


In [145]:
#14 Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b))


(array([1, 3, 5, 7], dtype=int64),)


In [146]:
#15 Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
print(a[index])

[ 5  6  7  8  9 10]


In [147]:
#16 Convert the function maxx that works on two scalars, to work on two arrays.
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [148]:
#17 Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
print(arr[:, [1,0,2]])

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [149]:
#18 Swap rows 1 and 2 in the array arr:
arr = np.arange(9).reshape(3,3)
print(arr[[1,0,2], :])


[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [150]:
#19 Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
print(arr[::-1])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [151]:
#20 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[8.328 5.057 5.54 ]
 [9.505 8.974 9.057]
 [8.201 8.124 5.728]
 [7.851 5.326 6.567]
 [6.085 7.635 7.136]]


In [152]:
#21 Print or show only 3 decimal places of the numpy array rand_arr.
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.983, 0.14 , 0.748],
       [0.789, 0.73 , 0.846],
       [0.556, 0.057, 0.887],
       [0.314, 0.56 , 0.254]])

In [153]:
#22 Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
print(rand_arr)

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]


In [154]:
#23 Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [155]:
#24 Print the full numpy array a without truncating.
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [189]:
#25 Create an arr with a range from 10 to 30 with a gap of 5
arr = np.arange( 10, 30, 5 )
print(arr)

[10 15 20 25]


In [190]:
#26 Swap rows 1 and 2 in the array arr:
arr = np.arange(9).reshape(3,3)
print(arr[[1,0,2], :])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [188]:
#Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print(a[index])

[ 6  9 10]


In [186]:
#28 Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [160]:
#29 Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
Smax, Smin = sepallength.max(), sepallength.min()
s = (sepallength - Smin)/(Smax - Smin)
print(s)

[0.222 0.167 0.111 0.083 0.194 0.306 0.083 0.194 0.028 0.167 0.306 0.139
 0.139 0.    0.417 0.389 0.306 0.222 0.389 0.222 0.306 0.222 0.083 0.222
 0.139 0.194 0.194 0.25  0.25  0.111 0.139 0.306 0.25  0.333 0.167 0.194
 0.333 0.167 0.028 0.222 0.194 0.056 0.028 0.194 0.222 0.139 0.222 0.083
 0.278 0.194 0.75  0.583 0.722 0.333 0.611 0.389 0.556 0.167 0.639 0.25
 0.194 0.444 0.472 0.5   0.361 0.667 0.361 0.417 0.528 0.361 0.444 0.5
 0.556 0.5   0.583 0.639 0.694 0.667 0.472 0.389 0.333 0.333 0.417 0.472
 0.306 0.472 0.667 0.556 0.361 0.333 0.333 0.5   0.417 0.194 0.361 0.389
 0.389 0.528 0.222 0.389 0.556 0.417 0.778 0.556 0.611 0.917 0.167 0.833
 0.667 0.806 0.611 0.583 0.694 0.389 0.417 0.583 0.611 0.944 0.944 0.472
 0.722 0.361 0.944 0.556 0.667 0.806 0.528 0.5   0.583 0.806 0.861 1.
 0.583 0.556 0.5   0.944 0.556 0.583 0.472 0.722 0.667 0.722 0.417 0.694
 0.667 0.667 0.556 0.611 0.528 0.444]


In [161]:
#30 Find the 5th and 95th percentile of iris's sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [162]:
#31 Insert np.nan values at 20 random positions in iris_2d dataset
i, j = np.where(iris_2d)
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 nan 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [163]:
#32 Convert numpy's datetime64 object to datetime's datetime object

dt64 = np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
dt64.tolist()


datetime.datetime(2018, 2, 25, 22, 10, 10)

In [164]:
#33 Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

print(seq(start, length, step))

[ 5  8 11 14 17 20 23 26 29 32]


In [165]:
#34 Find out if iris_2d has any missing values.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

In [166]:
#35 Replace all ccurrences of nan with 0 in numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
# Solution
iris_2d[np.isnan(iris_2d)] = 0
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.6 3.1 1.5 0.2]]


In [167]:
#36 Find the unique values and the count of unique values in iris's species
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
species = np.array([row.tolist()[4] for row in iris])
print(np.unique(species, return_counts=True))


(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype='|S15'), array([50, 50, 50], dtype=int64))


In [168]:
#37 Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

#Less than 3 --> 'small'
#3-5 --> 'medium'
#'>=5 --> 'large'

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]
print(petal_length_cat[:4])

['small', 'small', 'small', 'small']


In [169]:
#38 Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3
volume = volume[:, np.newaxis]
out = np.hstack([iris_2d, volume])
print(out[:4])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 38.13265162927291]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 35.200498485922445]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 30.0723720777127]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 33.238050274980004]]


In [170]:
#39 What is the value of second longest petallength of species setosa
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')
print(np.unique(np.sort(petal_len_setosa))[-2])

1.7


In [171]:
#40 Sort the iris dataset based on sepallength column.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[iris[:,0].argsort()][:20])


[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [172]:
#41 Find the most frequent value of petal length (3rd column) in iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


In [173]:
#42 Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
print(np.argwhere(iris[:, 3].astype(float) > 1.0)[0])

[50]


In [174]:
#43 From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.627 14.64  21.801 30.    10.    10.    30.    30.    10.    29.18
 30.    11.251 10.081 10.    11.765 30.    30.    10.    30.    14.43 ]


In [175]:
#44 Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a.argsort())

[ 4 13  5  8 17 12 11 14 19  1  2  0  9  6 16 18  7  3 10 15]


In [176]:
#45  Compute the counts of unique values row-wise.
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]


In [177]:
#46 Convert array_of_arrays into a flat linear 1d array.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]


In [178]:
#47 Create the ranks for the given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
# Solution
print(a.argsort().argsort())
print('Array: ', a)

[ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [179]:
#48 Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
print(np.amax(a, axis=1))

[9 8 6 3 9]


In [180]:
#49 Drop all nan values from a 1D numpy array
np.array([1,2,3,np.nan,5,6,7,np.nan])
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a[~np.isnan(a)])

[1. 2. 3. 5. 6. 7.]


In [181]:
#50 Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1])
                
print(a_2d - b_1d[:,None])

[[2 2 2]
 [3 3 3]
 [4 4 4]]
